### ISSUE TITLE
Firefox implementation

### ISSUE THREAD

**Issue by Artsassin** [Elias8477/YTQualityofLife#1]
Hi, I came upon your script after searching for extensions for the trash icon issue and would love to use it. However I primarily use firefox, is there a way to use it with this browser? Thank you for your hard work and reading.

**Comment by dselias** [comment]
Hello Artsassin! 
I've never developed anything for Firefox, and this extension is my first attempt on Chrome too. Both Firefox addons and Chrome extensions work on the same principle, so I think (and hope) it should work right out of the box. I am using the Chrome storage API for saving user preferences though so that might be one reason for the extension to break.

I don't have Firefox installed, and as of now I'm too busy to continue working on this extension besides patching minor bugs when things break due to updates on Youtube. This should give you the information on how to load the extension in Firefox: 
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension#installing

I've put your request on my todo list for when I have some free time.

**Comment by dselias** [comment]
The extension is now compatible with Firefox. Publishing add-ons doesn't require a fee unlike the Chrome Web Store so I have published it for ease of use.
https://addons.mozilla.org/en-US/firefox/addon/youtube-qolt/

**Comment by Artsassin** [comment]
Thank you so much dude <3

    On Wednesday, December 21, 2022 at 04:16:12 a.m. EST, Elias8477 ***@***.***> wrote:  
 
 


Closed #1 as completed.
